<?php

namespace App\Services\Accounting;

use App\Models\Expense;
use App\Models\Account;
use App\Exports\ExpenseExport;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Response;
use Carbon\Carbon;

class ExpenseService
{
    /**
     * Get expenses list with filters
     */
    public function getExpensesList(array $filters = [])
    {
        $query = Expense::with(['creator', 'category'])
            ->orderBy('expense_date', 'desc')
            ->orderBy('created_at', 'desc');

        // Apply filters
        if (!empty($filters['expense_category_id'])) {
            $query->where('expense_category_id', $filters['expense_category_id']);
        }

        // Backward compat: 'type' filter maps to expense_category_id
        if (!empty($filters['type'])) {
            $query->where('expense_category_id', $filters['type']);
        }

        if (!empty($filters['from_date'])) {
            $query->whereDate('expense_date', '>=', $filters['from_date']);
        }

        if (!empty($filters['to_date'])) {
            $query->whereDate('expense_date', '<=', $filters['to_date']);
        }

        $expenses = $query->paginate(20);

        // Calculate statistics
        $todayExpenses = Expense::whereDate('expense_date', Carbon::today())->sum('amount');
        $monthExpenses = Expense::whereYear('expense_date', Carbon::now()->year)
            ->whereMonth('expense_date', Carbon::now()->month)
            ->sum('amount');
        $totalExpenses = Expense::sum('amount');

        return compact('expenses', 'todayExpenses', 'monthExpenses', 'totalExpenses');
    }

    /**
     * Create new expense.
     *
     * 🐛 Bug Fix: تم إعادة كتابة الدالة لتستخدم الأعمدة الفعلية في DB:
     *  - expense_number (auto-generated via model boot)
     *  - expense_category_id (FK)
     *  - amount
     *  - expense_date
     *  - description
     *  - reference
     *  - created_by (FK to users)
     */
    public function createExpense(array $data)
    {
        try {
            // 1) Determine account based on payment method (cash → cash account, else bank)
            $accountType = ($data['payment_method'] ?? null) === 'cash' ? 'cash' : 'bank';
            $account = Account::where('type', $accountType)->first();

            if (! $account) {
                throw new \RuntimeException('الحساب غير موجود. يرجى إنشاء حساب ' . ($accountType === 'cash' ? 'نقدي' : 'بنكي') . ' أولاً.');
            }

            // 2) Check balance
            if ($account->balance < $data['amount']) {
                throw new \RuntimeException('الرصيد غير كافٍ في الحساب (المتاح: ' . number_format($account->balance, 2) . '، المطلوب: ' . number_format($data['amount'], 2) . ')');
            }

            // 3) Resolve category (must exist)
            $categoryId = $data['expense_category_id'] ?? null;
            if (! $categoryId) {
                throw new \RuntimeException('تصنيف المصروف مطلوب');
            }

            // 4) Create expense (expense_number auto-generated by model)
            $expense = Expense::create([
                'expense_category_id' => $categoryId,
                'amount'              => $data['amount'],
                'expense_date'        => $data['expense_date'] ?? $data['date'] ?? now()->toDateString(),
                'description'         => $data['description'] ?? $data['notes'] ?? null,
                'reference'           => $data['reference'] ?? $data['invoice_number'] ?? $data['reference_number'] ?? null,
                'attachment'          => $data['attachment'] ?? null,
                'created_by'          => Auth::id() ?? $data['created_by'] ?? null,
            ]);

            // 5) Deduct from account balance
            $account->decrement('balance', $data['amount']);

            // 6) Create transaction record
            $this->createExpenseTransaction($expense, $account);

            // 7) Log activity
            if (function_exists('activity')) {
                activity()
                    ->performedOn($expense)
                    ->causedBy(Auth::user())
                    ->withProperties(['amount' => $data['amount'], 'category_id' => $categoryId])
                    ->log('expense_created');
            }

            \Illuminate\Support\Facades\Log::info('Expense created', [
                'expense_id'     => $expense->id,
                'expense_number' => $expense->expense_number,
                'amount'         => $data['amount'],
            ]);

            return $expense;
        } catch (\Illuminate\Database\QueryException $e) {
            \Illuminate\Support\Facades\Log::error('DB error creating expense', [
                'error' => $e->getMessage(),
            ]);
            throw new \RuntimeException('حدث خطأ أثناء حفظ المصروف. تأكد من اختيار تصنيف صحيح.');
        } catch (\Exception $e) {
            \Illuminate\Support\Facades\Log::error('Error creating expense', [
                'error' => $e->getMessage(),
            ]);
            throw $e;
        }
    }

    /**
     * Get expense details.
     */
    public function getExpenseDetails($id)
    {
        return Expense::with(['creator', 'category'])->find($id);
    }

    /**
     * Update expense.
     */
    public function updateExpense($id, array $data)
    {
        try {
            $expense = Expense::find($id);

            if (! $expense) {
                return null;
            }

            // 1) If amount changed, we need to adjust account balance
            $oldAmount = (float) $expense->amount;
            $newAmount = (float) ($data['amount'] ?? $oldAmount);
            $difference = $newAmount - $oldAmount;

            if ($difference != 0) {
                $account = Account::where('type', 'cash')->first() ?? Account::first();

                if ($account) {
                    if ($difference > 0 && $account->balance < $difference) {
                        throw new \RuntimeException('الرصيد غير كافٍ لزيادة المبلغ');
                    }

                    if ($difference > 0) {
                        $account->decrement('balance', $difference);
                    } else {
                        $account->increment('balance', abs($difference));
                    }
                }
            }

            // 2) Update expense
            $payload = [];
            if (isset($data['expense_category_id'])) {
                $payload['expense_category_id'] = $data['expense_category_id'];
            }
            if (isset($data['amount'])) {
                $payload['amount'] = $data['amount'];
            }
            if (isset($data['expense_date']) || isset($data['date'])) {
                $payload['expense_date'] = $data['expense_date'] ?? $data['date'];
            }
            if (isset($data['description']) || isset($data['notes'])) {
                $payload['description'] = $data['description'] ?? $data['notes'];
            }
            if (isset($data['reference']) || isset($data['invoice_number']) || isset($data['reference_number'])) {
                $payload['reference'] = $data['reference'] ?? $data['invoice_number'] ?? $data['reference_number'];
            }

            if (! empty($payload)) {
                $expense->update($payload);
            }

            // 3) Log activity
            if (function_exists('activity')) {
                activity()
                    ->performedOn($expense)
                    ->causedBy(Auth::user())
                    ->withProperties(['old_amount' => $oldAmount, 'new_amount' => $newAmount])
                    ->log('expense_updated');
            }

            return $expense;
        } catch (\RuntimeException $e) {
            throw $e;
        } catch (\Illuminate\Database\QueryException $e) {
            \Illuminate\Support\Facades\Log::error('DB error updating expense', [
                'id'    => $id,
                'error' => $e->getMessage(),
            ]);
            throw new \RuntimeException('حدث خطأ أثناء تحديث المصروف.');
        } catch (\Exception $e) {
            \Illuminate\Support\Facades\Log::error('Error updating expense', [
                'id'    => $id,
                'error' => $e->getMessage(),
            ]);
            throw new \RuntimeException('حدث خطأ غير متوقع أثناء تحديث المصروف.');
        }
    }

    /**
     * Delete expense.
     */
    public function deleteExpense($id)
    {
        try {
            $expense = Expense::find($id);

            if (! $expense) {
                return false;
            }

            // Return money to cash account (default behavior)
            $account = Account::where('type', 'cash')->first() ?? Account::first();
            if ($account) {
                $account->increment('balance', $expense->amount);
            }

            // Log activity
            if (function_exists('activity')) {
                activity()
                    ->performedOn($expense)
                    ->causedBy(Auth::user())
                    ->withProperties(['amount' => $expense->amount])
                    ->log('expense_deleted');
            }

            $expense->delete();

            return true;
        } catch (\Illuminate\Database\QueryException $e) {
            \Illuminate\Support\Facades\Log::error('DB error deleting expense', [
                'id'    => $id,
                'error' => $e->getMessage(),
            ]);
            throw new \RuntimeException('لا يمكن حذف المصروف. قد يكون مرتبطاً ببيانات أخرى.');
        } catch (\Exception $e) {
            \Illuminate\Support\Facades\Log::error('Error deleting expense', [
                'id'    => $id,
                'error' => $e->getMessage(),
            ]);
            throw $e;
        }
    }

    /**
     * Get statistics — uses expense_date (DB column) and category relationship.
     */
    public function getStatistics($period = 'month')
    {
        $query = Expense::query();

        switch ($period) {
            case 'day':
                $query->whereDate('expense_date', Carbon::today());
                break;
            case 'week':
                $query->whereBetween('expense_date', [Carbon::now()->startOfWeek(), Carbon::now()->endOfWeek()]);
                break;
            case 'month':
                $query->whereMonth('expense_date', Carbon::now()->month)
                    ->whereYear('expense_date', Carbon::now()->year);
                break;
            case 'year':
                $query->whereYear('expense_date', Carbon::now()->year);
                break;
        }

        $total = (float) $query->sum('amount');
        $count = $query->count();
        $average = $count > 0 ? $total / $count : 0;

        // Get breakdown by category (using category_id)
        $byCategory = $query->select('expense_category_id', \DB::raw('SUM(amount) as total'))
            ->groupBy('expense_category_id')
            ->get()
            ->pluck('total', 'expense_category_id');

        return [
            'total' => $total,
            'count' => $count,
            'average' => $average,
            'by_category' => $byCategory,
        ];
    }

    /**
     * Get expenses by category (was getExpensesByType).
     */
    public function getExpensesByType($categoryId, $from = null, $to = null)
    {
        $query = Expense::where('expense_category_id', $categoryId);

        if ($from) {
            $query->whereDate('expense_date', '>=', $from);
        }

        if ($to) {
            $query->whereDate('expense_date', '<=', $to);
        }

        return $query->orderBy('expense_date', 'desc')->get();
    }

    /**
     * Bulk delete expenses.
     */
    public function bulkDelete(array $expenseIds)
    {
        $count = 0;
        foreach ($expenseIds as $id) {
            if ($this->deleteExpense($id)) {
                $count++;
            }
        }

        return $count;
    }

    /**
     * Get recurring expenses.
     */
    public function getRecurringExpenses()
    {
        // Identify expenses that repeat monthly (same category and similar amount)
        return Expense::select('expense_category_id', \DB::raw('AVG(amount) as avg_amount'), \DB::raw('COUNT(*) as frequency'))
            ->where('expense_date', '>=', Carbon::now()->subMonths(6))
            ->groupBy('expense_category_id')
            ->having('frequency', '>=', 3)
            ->get();
    }

    /**
     * 🐛 Note: approveExpense/rejectExpense — الـ DB لا يحتوي status/approved_by/approved_at.
     * نتركها كـ no-op placeholder حتى تضاف migration.
     */
    public function approveExpense($id)
    {
        $expense = Expense::find($id);
        if (! $expense) {
            return null;
        }
        \Illuminate\Support\Facades\Log::info('Expense approval requested (no status column in DB)', [
            'expense_id' => $id,
        ]);
        return $expense;
    }

    public function rejectExpense($id, $reason)
    {
        $expense = Expense::find($id);
        if (! $expense) {
            return null;
        }
        \Illuminate\Support\Facades\Log::info('Expense rejection requested (no status column in DB)', [
            'expense_id' => $id,
            'reason'     => $reason,
        ]);
        return $expense;
    }

    /**
     * Export تقرير المصروفات إلى Excel.
     *
     * @param  array  $filters  ['type', 'from_date', 'to_date', 'payment_method', 'status']
     * @return \Symfony\Component\HttpFoundation\BinaryFileResponse
     */
    public function exportReport(array $filters)
    {
        $filename = 'expenses_'.now()->format('Ymd_His').'.xlsx';

        return \Maatwebsite\Excel\Facades\Excel::download(
            new ExpenseExport($filters),
            $filename
        );
    }

    /**
     * Create expense transaction record (in cash_transactions table).
     *
     * 🐛 Bug Fix: كان يستخدم \App\Models\Transaction (غير موجود)
     * الآن يستخدم CashTransaction الموجود فعلياً.
     */
    private function createExpenseTransaction($expense, $account): void
    {
        try {
            DB::table('cash_transactions')->insert([
                'transaction_number' => 'EXP-TX-' . $expense->id,
                'transaction_type'   => 'expense',
                'amount'             => (float) $expense->amount,
                'transaction_date'   => $expense->expense_date ?? now()->toDateString(),
                'category'           => 'expense',
                'description'        => "مصروف رقم {$expense->expense_number}" . ($expense->description ? " - {$expense->description}" : ''),
                'reference'          => $expense->expense_number,
                'created_by'         => $expense->created_by ?? Auth::id(),
                'created_at'         => now(),
                'updated_at'         => now(),
            ]);
        } catch (\Exception $e) {
            \Illuminate\Support\Facades\Log::warning('Failed to create expense transaction', [
                'expense_id' => $expense->id,
                'error'       => $e->getMessage(),
            ]);
            // لا نرمي exception - الـ expense تم إنشاؤه بنجاح
        }
    }
}