"""
Magzani ERP Doc - Part 3
Database Schema (Central + Tenant complete)
"""
import sys
sys.path.insert(0, r"C:\MAGZANIV6\Magzani\docs")
from _build_doc_part2 import (
    doc, add_heading, add_para, add_para_rtl, add_table, add_code_block,
    add_hr, add_page_break, OUT_PATH,
)
from docx.shared import Pt, Cm, RGBColor

# ============================================================
# PART 3 - DATABASE SCHEMA
# ============================================================
add_page_break(doc)
add_heading(doc, 'Part 3: Database Schema', level=1)

add_para(doc,
    'Magzani uses a database-per-tenant architecture. The central MySQL database holds tenant, domain, '
    'and plan tables. Each tenant gets its own MySQL database named tenant{tenant_id}, with all business '
    'tables (products, invoices, accounting, etc.).'

)

# ----- CENTRAL DB -----
add_heading(doc, '3.1 Central (Landlord) Database Tables', level=2)

add_heading(doc, 'tenants', level=3)
add_para(doc, 'Stancl default + custom columns. Source-of-truth for each tenant organization.')
add_table(doc, ['Column', 'Type', 'Notes'],
    [
        ['id', 'string (UUID)', 'PK, generated by Stancl\\Tenancy\\UUIDGenerator'],
        ['data', 'JSON', 'Stancl flexible store — plan_id stored here'],
        ['plan_id', '(from data)', 'FK to plans.slug, stored in JSON'],
        ['plan_expires_at', 'timestamp', 'Added by migration 2026_06_05_000002'],
        ['trial_ends_at', 'timestamp', 'Added by migration 2026_06_05_000002'],
        ['is_suspended', 'bool (from data)', 'Tenant suspension flag'],
        ['created_at / updated_at', 'timestamps', ''],
    ], col_widths=[Cm(5), Cm(4), Cm(7)], font_size=9)

add_heading(doc, 'domains', level=3)
add_para(doc, 'Stancl default. Stores the domain-to-tenant mapping (e.g. acme.localhost → tenant id abc-123).')
add_table(doc, ['Column', 'Type', 'Notes'],
    [
        ['id', 'bigint', 'PK'],
        ['domain', 'string (unique)', 'Full hostname, e.g. "acme.localhost"'],
        ['tenant_id', 'string FK', 'FK → tenants.id'],
        ['created_at / updated_at', 'timestamps', ''],
    ], col_widths=[Cm(5), Cm(4), Cm(7)], font_size=9)

add_heading(doc, 'plans', level=3)
add_table(doc, ['Column', 'Type', 'Notes'],
    [
        ['id', 'bigint', 'PK'],
        ['slug', 'string (unique)', 'starter, pro, enterprise, custom...'],
        ['name', 'string', 'Display name (Arabic / English)'],
        ['description', 'text', ''],
        ['price', 'decimal(10,2)', ''],
        ['billing_period', 'string', 'monthly | yearly'],
        ['features', 'JSON', 'Feature flag toggles'],
        ['is_active', 'bool', ''],
        ['created_at / updated_at', 'timestamps', ''],
    ], col_widths=[Cm(5), Cm(4), Cm(7)], font_size=9)

add_heading(doc, 'plan_features', level=3)
add_table(doc, ['Column', 'Type', 'Notes'],
    [
        ['id', 'bigint', 'PK'],
        ['plan_id', 'bigint FK', 'FK → plans.id'],
        ['feature_key', 'string', 'pos, manufacturing, multi_warehouse...'],
        ['is_enabled', 'bool', ''],
        ['limit_value', 'integer (nullable)', 'Optional numeric cap (e.g. max warehouses = 5)'],
    ], col_widths=[Cm(5), Cm(4), Cm(7)], font_size=9)

# ----- TENANT DB -----
add_page_break(doc)
add_heading(doc, '3.2 Tenant Database Schema (per-tenant DB)', level=2)
add_para(doc, 'Each tenant DB contains ALL the tables below. There are ~70+ tables grouped by module:')

add_heading(doc, '3.2.1 Auth & RBAC (5 tables)', level=3)
add_table(doc, ['Table', 'Key Columns', 'Purpose'],
    [
        ['users', 'id, name, email (unique), password, phone, is_active, role (admin/employee), remember_token, soft_deletes',
         'User accounts — admin & employee'],
        ['roles', 'id, name, display_name (AR), description, color, is_system, timestamps',
         'Permission roles'],
        ['permissions', 'id, name, display_name, description, module, action, timestamps',
         'Granular permissions per module/action'],
        ['role_user', 'user_id, role_id, timestamps', 'Pivot: users ↔ roles'],
        ['permission_role', 'permission_id, role_id, timestamps', 'Pivot: permissions ↔ roles'],
    ], col_widths=[Cm(3.5), Cm(8), Cm(4.5)], font_size=9)

add_heading(doc, '3.2.2 Catalog - Products & Pricing (~12 tables)', level=3)
add_table(doc, ['Table', 'Key Columns'],
    [
        ['categories', 'id, name, description, parent_id, is_active, timestamps'],
        ['products', 'id, name, code, sku, barcode, description, category_id, brand_id, unit_id, base_unit, base_unit_label, purchase_price, selling_price, min_selling_price, wholesale_price, tax_rate, default_discount, profit_margin, stock_alert_quantity, reorder_level, reorder_quantity, min_stock, max_stock, weight, dimensions, image, is_active, is_featured, has_expiry, track_serial, category (legacy), notes, status, product_type, is_manufactured, timestamps, soft_deletes'],
        ['product_warehouse', 'product_id, warehouse_id, quantity, reserved_quantity, available_quantity, min_stock, average_cost, last_count_quantity, last_count_date, adjustment_total, timestamps'],
        ['units', 'id, name, abbreviation, conversion_factor, timestamps'],
        ['product_base_pricing', 'product_id, base_purchase_price, base_selling_price, is_active, is_current'],
        ['product_price_history', 'product_id, old_price, new_price, change_type, changed_by, changed_at'],
        ['product_base_units', 'product_id, unit_name, unit_code, quantity_in_base_unit'],
        ['product_selling_units', 'product_id, unit_name, unit_code, conversion_factor, label, selling_price, purchase_price, is_default, is_base'],
        ['product_sales_units', 'similar to selling_units'],
        ['unit_conversions', 'from_unit_id, to_unit_id, factor, type'],
        ['price_change_history', 'Bulk price change audit trail'],
        ['supplier_product_prices', 'supplier_id, product_id, price, min_quantity, valid_from, valid_to'],
    ], col_widths=[Cm(5), Cm(11)], font_size=9)

add_heading(doc, '3.2.3 Warehouses & Transfers (6 tables)', level=3)
add_table(doc, ['Table', 'Key Columns'],
    [
        ['warehouses', 'id, name, location, manager, is_active, timestamps, soft_deletes'],
        ['warehouse_transfers', 'id, transfer_number, from_warehouse_id, to_warehouse_id, status (draft/pending/in_transit/received/cancelled/reversed), transfer_date, expected_arrival, notes, created_by, timestamps, soft_deletes'],
        ['warehouse_transfer_items', 'id, transfer_id, product_id, quantity, unit, unit_cost, total'],
        ['warehouse_inbound_orders', 'id, order_number, warehouse_id, supplier_id, status, expected_date, received_date, notes'],
        ['warehouse_inbound_order_items', 'inbound_id, product_id, quantity, unit_cost, total_cost'],
        ['warehouse_outbound_orders', 'id, order_number, warehouse_id, customer_id, status, expected_date, shipped_date'],
        ['warehouse_outbound_order_items', 'outbound_id, product_id, quantity, unit_cost, total_cost'],
    ], col_widths=[Cm(5), Cm(11)], font_size=9)

add_heading(doc, '3.2.4 Sales (4 tables)', level=3)
add_table(doc, ['Table', 'Key Columns'],
    [
        ['sales_invoices', 'id, invoice_number, customer_id, warehouse_id, invoice_date, due_date, subtotal, discount_type/value/amount, tax_rate/amount, shipping_cost, other_charges, total, paid, status (draft/confirmed/cancelled), payment_status (paid/partial/unpaid), notes, confirmed_by/at, shift_id, source (pos/manual), payment_method, journal_entry_id, cogs_entry_id, soft_deletes'],
        ['sales_invoice_items', 'id, invoice_id, product_id, quantity, unit, base_quantity, unit_price, discount_*, tax_*, total, cost_price, profit'],
        ['sales_returns', 'id, return_number, invoice_id, customer_id, warehouse_id, return_date, subtotal, total, notes, reason, status, shift_id, created_by, soft_deletes'],
        ['sales_return_items', 'id, return_id, invoice_item_id, product_id, quantity, unit_price, total'],
    ], col_widths=[Cm(3.5), Cm(12)], font_size=9)

add_heading(doc, '3.2.5 Purchases (4 tables)', level=3)
add_table(doc, ['Table', 'Key Columns'],
    [
        ['purchase_invoices', 'id, invoice_number, supplier_id, warehouse_id, invoice_date, due_date, subtotal, discount_*, tax_*, total, paid, status, payment_status, notes, confirmed_by/at, journal_entry_id, soft_deletes'],
        ['purchase_invoice_items', 'id, invoice_id, product_id, quantity, base_quantity, unit, cost, total'],
        ['purchase_returns', 'id, return_number, invoice_id, supplier_id, warehouse_id, return_date, total, reason, status, soft_deletes'],
        ['purchase_return_items', 'id, return_id, invoice_item_id, product_id, quantity, unit_cost, total'],
    ], col_widths=[Cm(3.5), Cm(12)], font_size=9)

add_heading(doc, '3.2.6 Partners (4 tables)', level=3)
add_table(doc, ['Table', 'Key Columns'],
    [
        ['customers', 'id, name, phone, email, address, contact_person, opening_balance, current_balance (updated 2026_04_07), credit_limit, is_active, code, soft_deletes'],
        ['suppliers', 'id, name, phone, email, address, contact_person, opening_balance, current_balance, is_active, code, soft_deletes'],
        ['supplier_payments', 'id, supplier_id, invoice_id, amount, payment_date, payment_method, notes, journal_entry_id, created_by'],
        ['supplier_product_prices', 'id, supplier_id, product_id, price, min_quantity, valid_from, valid_to, notes'],
    ], col_widths=[Cm(3.5), Cm(12)], font_size=9)

add_heading(doc, '3.2.7 Payments (3 tables)', level=3)
add_table(doc, ['Table', 'Key Columns'],
    [
        ['payments', 'id, payable_id, payable_type (polymorphic), amount, payment_date, payment_method, reference, notes, created_by, journal_entry_id'],
        ['invoice_payments', 'legacy duplicate of payments'],
        ['customer_refunds', 'id, customer_id, invoice_id, amount, refund_date, method, journal_entry_id, notes, created_by'],
    ], col_widths=[Cm(4), Cm(12)], font_size=9)

add_heading(doc, '3.2.8 Stock Operations (3 tables)', level=3)
add_table(doc, ['Table', 'Key Columns'],
    [
        ['stock_adjustments', 'id, product_id, warehouse_id, quantity, type, reason, notes, user_id'],
        ['stock_counts', 'id, count_number, warehouse_id, count_date, status (draft/pending/in_transit/received/cancelled/reversed), started_at, completed_at, cancelled_at, notes, created_by, approved_by, soft_deletes'],
        ['stock_count_items', 'id, stock_count_id, product_id, system_quantity, counted_quantity, difference, reason, approved, approved_by'],
    ], col_widths=[Cm(4), Cm(12)], font_size=9)

add_heading(doc, '3.2.9 Inventory Movements (1 table)', level=3)
add_table(doc, ['Table', 'Key Columns'],
    [
        ['inventory_movements', 'id, product_id, warehouse_id, type (initial_stock/purchase/sale/transfer/adjustment/return/production), quantity, unit_cost, total_cost, reference_type, reference_id, notes, created_by (nullable per 2026_03_01), movement_date'],
    ], col_widths=[Cm(4), Cm(12)], font_size=9)

add_heading(doc, '3.2.10 Cash & Expenses (3 tables)', level=3)
add_table(doc, ['Table', 'Key Columns'],
    [
        ['cash_transactions', 'id, type (deposit/withdrawal), amount, transaction_date, reference, notes, created_by, balance_after'],
        ['expenses', 'id, expense_category_id, amount, expense_date, description, payment_method, reference, created_by'],
        ['expense_categories', 'id, name, description, is_active'],
    ], col_widths=[Cm(4), Cm(12)], font_size=9)

add_heading(doc, '3.2.11 Manufacturing (5 tables)', level=3)
add_table(doc, ['Table', 'Key Columns'],
    [
        ['manufacturing_costs', 'id, product_id, labor_cost, material_cost, overhead_cost, total_cost, cost_per_unit, profit_margin, selling_price, notes'],
        ['bom_components', 'id, manufacturing_cost_id, product_id, material_name, quantity, unit, unit_cost, total_cost, component_type (varchar)'],
        ['manufacturing_orders', 'id, order_number (MO-YYYY-NNNN), product_id (nullable FK), product_name, quantity_produced, cost_per_unit, total_cost, selling_price_per_unit, status, produced_at, notes, warehouse_id, created_by, updated_by, completed_by, soft_deletes'],
        ['manufacturing_order_components', 'id, order_id, component_name, quantity, unit, unit_cost, total_cost, wood_stock_id, component_type, specs'],
        ['raw_material_templates', 'id, name, description, is_active, timestamps'],
    ], col_widths=[Cm(4.5), Cm(11)], font_size=9)

add_heading(doc, '3.2.12 Wood Stock & Dispensing (2 tables)', level=3)
add_table(doc, ['Table', 'Key Columns'],
    [
        ['wood_stocks', 'id, wood_type, quantity, unit, warehouse_id (added 2026_*), product_id (added), timestamps'],
        ['wood_dispensings', 'id, wood_stock_id, quantity, dispensed_to, dispensing_date, invoice_id (added), notes, created_by'],
    ], col_widths=[Cm(4.5), Cm(11)], font_size=9)

add_heading(doc, '3.2.13 Accounting (~14 tables)', level=3)
add_table(doc, ['Table', 'Key Columns'],
    [
        ['accounts', 'id, code (unique), name, type (asset/liability/equity/revenue/expense), parent_id, normal_balance, is_active, description'],
        ['account_types', 'id, name, category (asset/liability/equity/revenue/expense), normal_balance'],
        ['account_balances', 'id, account_id, fiscal_year_id, opening_balance, debit_total, credit_total, closing_balance, balance_date'],
        ['journal_entries', 'id, entry_number, entry_date, description, source (manual/system), status (draft/posted/reversed), fiscal_year_id, fiscal_period_id, reference_type, reference_id, total_debit, total_credit, created_by, posted_by, posted_at, reversed_by, reversed_at, reversal_of'],
        ['journal_entry_lines', 'id, journal_entry_id, account_id, debit, credit, description, cost_center_id, partner_type, partner_id, line_order'],
        ['recurring_journal_entries', 'id, template_name, frequency, start_date, end_date, last_run_date, next_run_date, is_active, description, total_amount'],
        ['recurring_journal_entry_lines', 'id, recurring_id, account_id, debit, credit, description'],
        ['fiscal_years', 'id, name, start_date, end_date, is_current, is_closed, closed_at'],
        ['fiscal_periods', 'id, fiscal_year_id, name, start_date, end_date, period_number, is_closed'],
        ['accounting_settings', 'id, setting_key, setting_value'],
        ['accounting_audit_logs', 'audit trail for posting'],
        ['accounting_posting_failures', 'id, transaction_type, reference_id, error_message, retry_count, resolved_at'],
        ['bank_accounts', 'id, name, account_number, bank_name, currency, opening_balance, current_balance'],
        ['bank_reconciliations', 'id, bank_account_id, statement_date, statement_balance, book_balance, difference'],
        ['cost_centers', 'id, name, code, description, is_active'],
        ['fixed_assets', 'id, name, code, purchase_date, purchase_cost, salvage_value, useful_life, depreciation_method, accumulated_depreciation, book_value, status'],
        ['fixed_asset_depreciations', 'id, fixed_asset_id, depreciation_date, amount, accumulated_depreciation, book_value'],
    ], col_widths=[Cm(4.5), Cm(11)], font_size=9)

add_heading(doc, '3.2.14 Misc Tables', level=3)
add_table(doc, ['Table', 'Key Columns'],
    [
        ['companies', 'id, name, logo, address, phone, email, tax_id, currency'],
        ['system_settings', 'id, key, value, timestamps'],
        ['activity_logs', 'id, user_id, action, model_type, model_id, description, properties (JSON), created_at'],
        ['invoice_sequences', 'per-type invoice numbering tracking'],
        ['invoice_activity_log', 'invoice-specific event tracking'],
        ['notifications', 'Standard Laravel notifications table'],
    ], col_widths=[Cm(4.5), Cm(11)], font_size=9)

add_heading(doc, '3.3 Key Model Relationships Summary', level=2)
add_table(doc, ['Parent Model', 'hasMany', 'belongsTo'],
    [
        ['Warehouse', 'products (via ProductWarehouse), transfers (from/to), inboundOrders, outboundOrders, stockCounts',
         'creator/approver (User)'],
        ['Customer', 'salesInvoices, salesReturns, payments, refunds', 'createdBy (User)'],
        ['Supplier', 'purchaseInvoices, purchaseReturns, payments, productPrices', 'createdBy (User)'],
        ['Product', 'invoiceItems (sales+purchase), returnItems, warehouseStocks, movements, priceHistory',
         'category, brand, unit, baseUnit'],
        ['SalesInvoice', 'items, returns, payments (polymorphic), inventoryMovements',
         'customer, warehouse, shift, confirmedBy (User)'],
        ['PurchaseInvoice', 'items, returns, payments (polymorphic)',
         'supplier, warehouse, confirmedBy (User)'],
        ['PosShift', 'salesInvoices (source=pos)',
         'user (User), closingBy'],
        ['ManufacturingOrder', 'components, costs',
         'product, warehouse, createdBy/completedBy (User)'],
        ['Account', 'balances, journalEntryLines, parent/children',
         'accountType, parent'],
        ['JournalEntry', 'lines, recurringLines',
         'fiscalYear, fiscalPeriod, createdBy (User)'],
        ['User', 'salesInvoices, purchaseInvoices, salesReturns, purchaseReturns, transfers, payments, expenses, cashTransactions, activityLogs',
         'role (via role_user pivot), permissions'],
    ], col_widths=[Cm(3.5), Cm(7), Cm(5)], font_size=9)

doc.save(OUT_PATH)
print(f"Part 3 appended → {OUT_PATH}")
